title: Researcher
url: "https://alessandrastampi-bombelli.com"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home/"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
